Repository woowa-techcamp-2020/todo-2, pull requests merged in 2020-07, with the labels that each got.

#6 [#2] style(default) - 공통 스타일 설정
  public/stylesheets/scss/_definitions.scss
  public/stylesheets/scss/base.scss
Labels: feature, frontend, setting

#11 [#2] style(setting) - 폰트 적용
  public/stylesheets/scss/_definitions.scss
  public/stylesheets/scss/base.scss
Labels: feature, frontend, setting

#9 [#8] style(menu bar) - 메뉴바 설정
  public/stylesheets/scss/header.scss
  views/Header.pug
  views/index.pug
Labels: feature, frontend

#12 [#4] feature(side bar) - 이벤트 처리
  public/javascripts/SideBar.js
  public/stylesheets/scss/header.scss
  public/stylesheets/scss/sidebar.scss
  views/Header.pug
  views/Sidebar.pug
Labels: feature, frontend

#15 Feature/7 column style
  .gitignore
  public/images/plus-btn.svg
  public/images/remove-btn.svg
  public/stylesheets/scss/_definitions.scss
  public/stylesheets/scss/column.scss
  views/Column.pug
  views/index.pug
Labels: feature, frontend

#13 [#4] refactor(side bar) - 코드리뷰 바탕 수정
  public/icon/close.png
  public/javascripts/Constants.js
  public/javascripts/SideBar.js
  public/stylesheets/scss/base.scss
  public/stylesheets/scss/cardEditModal.scss
  public/stylesheets/scss/header.scss
  public/stylesheets/scss/sidebar.scss
  views/CardEditModal.pug
  views/Sidebar.pug
  views/index.pug
Labels: feature, frontend

#16 Feature/14 divide card form
  public/stylesheets/scss/cardForm.scss
  public/stylesheets/scss/column.scss
  views/CardForm.pug
  views/Column.pug
  views/index.pug
Labels: enhancement, frontend

#19 [#18] refactor(style) - scss, javascripts 폴더 구조 변경
  public/javascripts/components/SideBar.js
  public/javascripts/utils/Constants.js
  public/stylesheets/scss/common/_definitions.scss
  public/stylesheets/scss/common/base.scss
  public/stylesheets/scss/components/cardEditModal.scss
  public/stylesheets/scss/components/cardForm.scss
  public/stylesheets/scss/components/column.scss
  public/stylesheets/scss/components/header.scss
  public/stylesheets/scss/components/sidebar.scss
  views/CardEditModal.pug
  views/Sidebar.pug
  views/index.pug
Labels: enhancement, frontend, setting

#20 Feature/5 card style
  public/images/document.svg
  public/stylesheets/scss/components/card.scss
  views/Card.pug
  views/Column.pug
  views/index.pug
Labels: feature, frontend

#23 Feature/21 login style
  public/stylesheets/scss/components/loginForm.scss
  src/router.js
  views/LoginForm.pug
  views/index.pug
Labels: feature, frontend

#24 [#5] fix(card) - 카드 마진 적용 및 스크롤 위치 변경
  public/stylesheets/scss/components/card.scss
  public/stylesheets/scss/components/column.scss
  views/Column.pug
Labels: enhancement, frontend

#31 Feature/25 webpack
  package-lock.json
  package.json
  public/images/close.png
  public/images/menu.png
  public/images/notification.png
  public/javascripts/components/Card.js
  public/javascripts/components/CardForm.js
  public/javascripts/components/Column.js
  public/javascripts/components/DeleteCardModal.js
  public/javascripts/components/EditCardModal.js
  public/javascripts/components/EditColumnModal.js
  public/javascripts/components/Header.js
  public/javascripts/components/LoginForm.js
  public/javascripts/components/Modal.js
  public/javascripts/components/SideBar.js
  public/javascripts/components/SideBarCard.js
  public/javascripts/index.js
  public/stylesheets/common/_definitions.scss
  public/stylesheets/common/base.scss
  public/stylesheets/components/card.scss
  public/stylesheets/components/cardForm.scss
  public/stylesheets/components/column.scss
  public/stylesheets/components/header.scss
  public/stylesheets/components/loginForm.scss
  public/stylesheets/components/modal.scss
  public/stylesheets/components/sidebar.scss
  views/Modal.pug
  views/Sidebar.pug
  views/index.pug
  webpack.config.js
Labels: enhancement, frontend, setting

#36 Feature/35 column component
  public/javascripts/components/Column.js
  public/javascripts/index.js
  views/index.pug
Labels: feature, frontend

#40 Feature/26 card add event
  package-lock.json
  package.json
  public/javascripts/components/Card.js
  public/javascripts/components/CardForm.js
  public/javascripts/components/Column.js
  public/javascripts/index.js
  public/javascripts/utils/Constants.js
  public/javascripts/utils/HtmlGenerator.js
  public/stylesheets/components/cardForm.scss
  public/stylesheets/components/column.scss
  views/index.pug
Labels: enhancement, feature, frontend

#41 Feature/26 card add event
  public/javascripts/components/Card.js
  public/javascripts/components/CardForm.js
  public/javascripts/components/Column.js
  public/javascripts/utils/Constants.js
  public/javascripts/utils/EventEmitter.js
Labels: enhancement, feature, frontend

#42 Feature/27 remove card
  public/javascripts/components/Card.js
  public/javascripts/utils/Constants.js
  public/stylesheets/components/card.scss
Labels: feature, frontend

#43 Feature/35 column component
  public/javascripts/components/Card.js
  public/javascripts/components/CardForm.js
  public/javascripts/components/Column.js
  public/javascripts/index.js
Labels: feature, frontend

#45 Feature/26 card add event
  public/javascripts/components/Card.js
  public/javascripts/components/CardForm.js
  public/javascripts/components/Column.js
  public/javascripts/index.js
  public/javascripts/utils/Constants.js
  public/javascripts/utils/EventEmitter.js
Labels: enhancement, frontend

#46 Feature/27 remove card
  public/javascripts/components/Card.js
  public/javascripts/components/Column.js
  public/javascripts/index.js
  public/javascripts/utils/Constants.js
  public/stylesheets/components/card.scss
Labels: feature, frontend

#48 Feature/47 column index
  public/javascripts/components/Card.js
  public/javascripts/components/Column.js
Labels: feature, frontend

#54 Feature/53 delete card
  public/javascripts/components/Card.js
  public/javascripts/components/Column.js
  public/javascripts/components/Modal/DeleteCardModal.js
  public/stylesheets/common/_definitions.scss
  public/stylesheets/components/modal.scss
Labels: feature, frontend

#58 [#4] style(sidebar) - 초 변경, 마진 추가
  public/stylesheets/components/sidebar.scss
  views/Sidebar.pug
Labels: frontend

#55 [#28] refacotr(editCard) - addEvent 미사용
  public/javascripts/components/Modal/EditCardModal.js
Labels: bug, frontend

#56 [#3] refacotr(Modal) - addEvent 미사용
  public/javascripts/components/Modal/Modal.js
Labels: bug, frontend

#57 [#29] refacotr(editColumn) - addEvent 미사용
  public/javascripts/components/Modal/EditColumnModal.js
Labels: bug, frontend

#59 Feature/33 drag drop
  public/javascripts/components/Card.js
  public/javascripts/index.js
  public/stylesheets/common/base.scss
  public/stylesheets/components/card.scss
Labels: feature, frontend

#66 Feature/64 event refactoring
  public/javascripts/components/Card.js
  public/javascripts/components/CardForm.js
  public/javascripts/components/Column.js
  public/javascripts/index.js
  public/javascripts/utils/Constants.js
  public/stylesheets/common/base.scss
  public/stylesheets/components/card.scss
  public/stylesheets/components/cardForm.scss
  public/stylesheets/components/column.scss
Labels: enhancement, feature, frontend

#70 [#69] feature(activityTable) - 액티비티 카드 스타일링
  public/stylesheets/components/sidebar.scss
  views/ActivityCard.pug
  views/Sidebar.pug
  views/SidebarCard.pug
Labels: feature, frontend

#73 Feature/67 card move end
  public/javascripts/components/Card.js
  public/javascripts/components/Column.js
  public/javascripts/index.js
  public/javascripts/utils/Constants.js
  public/javascripts/utils/EventEmitter.js
Labels: enhancement, feature, frontend

#81 [#79] fix(card) - 카드 아이디 중복되는 버그 해결
  public/javascripts/components/Column.js
Labels: bug, frontend

#72 Feature/71 activity card
  public/javascripts/components/ActivityCard.js
  public/javascripts/index.js
  public/javascripts/utils/Constants.js
  public/stylesheets/components/sidebar.scss
  views/ActivityCard.pug
  views/Sidebar.pug
Labels: feature, frontend

#85 Feature/78 init render
  public/javascripts/api/index.js
  public/javascripts/index.js
  src/controller.js
  src/model.js
  src/router.js
Labels: backend, feature

#86 Feature/84 edit column title
  public/javascripts/api/index.js
  public/javascripts/components/Column.js
  public/javascripts/index.js
  src/controller.js
  src/model.js
  src/router.js
Labels: backend, feature

#89 Feature/82 delete card
  public/javascripts/api/index.js
  public/javascripts/components/Card.js
  src/controller.js
  src/model.js
  src/router.js
Labels: backend, feature

#90 Feature/77 card add api
  public/javascripts/api/index.js
  public/javascripts/components/Column.js
  src/controller.js
  src/model.js
  src/router.js
Labels: backend, feature

#101 [#77] style(card) - 카드 이동시 grabbing 커서로 변경
  public/javascripts/components/Card.js
  public/javascripts/utils/Constants.js
  public/stylesheets/common/base.scss
  public/stylesheets/components/card.scss
Labels: enhancement, frontend

#102 [#100] feature(showActivityTime) - 시간 포맷 설정
  public/javascripts/components/ActivityCard.js
  public/javascripts/index.js
  public/javascripts/utils/Constants.js
Labels: feature, frontend

#103 Feature/96 card move api
  app.js
  public/javascripts/api/index.js
  public/javascripts/components/Card.js
  src/controller.js
  src/model.js
  src/router.js
Labels: backend, feature

#112 [#109] feature(activityServerAPI) - 서버API 생성
  public/javascripts/api/index.js
  public/javascripts/index.js
  src/controller.js
  src/model.js
  src/router.js
Labels: backend, feature

#107 Feature/96 card move api
  public/javascripts/api/index.js
  public/javascripts/components/Card.js
  src/controller.js
  src/model.js
  src/router.js
Labels: backend, feature, frontend

#106 [#105] fix(column) - 초기 렌더링시 카드 순서를 nextCardId 기준으로 정렬
  public/javascripts/components/Column.js
  public/javascripts/index.js
Labels: bug, enhancement, frontend

#108 Feature/104 activity client api
  public/javascripts/api/index.js
  public/javascripts/components/ActivityCard.js
  public/javascripts/index.js
  public/javascripts/utils/Constants.js
  public/stylesheets/components/sidebar.scss
  src/controller.js
  src/model.js
  src/router.js
Labels: feature, frontend

#118 Feature/113 add column
  public/javascripts/api/index.js
  public/javascripts/components/Column.js
  public/javascripts/components/ColumnForm.js
  public/javascripts/index.js
  public/javascripts/utils/Constants.js
  public/stylesheets/components/columnForm.scss
  src/controller.js
  src/model.js
  src/router.js
Labels: backend, feature, frontend

#119 Feature/114 remove column
  public/javascripts/api/index.js
  public/javascripts/components/Column.js
  src/controller.js
  src/model.js
  src/router.js
Labels: backend, feature, frontend

#121 Refactor/98 button disable
  public/javascripts/components/Modal/EditCardModal.js
  public/javascripts/components/Modal/EditColumnModal.js
  public/stylesheets/components/modal.scss
Labels: feature, frontend

#122 [#120] fix(card) - 스크롤 생길시 드래그 이벤트 위치가 이상해지는 버그 해결
  public/javascripts/components/Card.js
  public/javascripts/components/Column.js
Labels: bug, enhancement, frontend

#124 [#99] feature(escapekeyDown) - esc키 누를 때 모달 없애기
  public/javascripts/components/Modal/DeleteCardModal.js
  public/javascripts/components/Modal/Modal.js
Labels: feature, frontend

#116 [#115] feature(editColumnAPI) - 컬럼 수정 api
  public/javascripts/components/ActivityCard.js
  public/javascripts/index.js
  public/javascripts/utils/Constants.js
Labels: backend, feature

#127 Feature/123 move column
  public/javascripts/components/Card.js
  public/javascripts/components/Column.js
  public/javascripts/utils/Constants.js
  public/javascripts/utils/DragDrop.js
  public/stylesheets/components/column.scss
Labels: enhancement, feature, frontend

#128 Feature/126 card activity
  public/javascripts/api/index.js
  public/javascripts/components/Card.js
  public/javascripts/index.js
  src/controller.js
  src/model.js
  src/router.js
Labels: backend, feature

#133 [#130] fix(drag event) - pointerdown 이벤트가 발생하면 안 되는 곳 바로 리턴
  public/javascripts/components/Board.js
  public/javascripts/components/Column.js
  public/javascripts/utils/Constants.js
  public/stylesheets/components/cardForm.scss
  public/stylesheets/components/column.scss
Labels: bug, enhancement, frontend

#132 Feature/126 card activity
  public/javascripts/components/Card.js
  public/javascripts/components/Column.js
Labels: backend, feature

#138 [#137] feature(modalEnter) - 수정모달 엔터시 저장
  public/javascripts/components/Modal/EditColumnModal.js
Labels: feature, frontend

#136 Feature/134 column activity
  public/javascripts/components/Board.js
  public/javascripts/components/Column.js
Labels: backend, feature

#140 Feature/135 login
  app.js
  package-lock.json
  package.json
  public/javascripts/api/index.js
  public/javascripts/components/ActivityCard.js
  public/javascripts/components/Board.js
  public/javascripts/components/Header.js
  public/javascripts/components/LoginForm.js
  public/javascripts/components/SideBar.js
  public/javascripts/components/SideBarCard.js
  public/javascripts/index.js
  public/javascripts/utils/Constants.js
  public/stylesheets/components/activityCard.scss
  public/stylesheets/components/header.scss
  public/stylesheets/components/loginForm.scss
  public/stylesheets/components/sidebar.scss
  src/controller.js
  src/model.js
  src/router.js
  views/ActivityCard.pug
  views/Header.pug
  views/LoginForm.pug
  views/Sidebar.pug
  views/index.pug
Labels: backend, feature

#142 Feature/141 logout
  public/javascripts/api/index.js
  public/javascripts/components/Header.js
  src/controller.js
  src/router.js
Labels: backend, feature, frontend

#145 Feature/144 card username
  public/javascripts/components/Board.js
  public/javascripts/components/Column.js
  public/javascripts/components/LoginForm.js
Labels: enhancement, feature, frontend

#147 [#146] refactor(activity) - 액티비티 저장시 username 저장
  public/javascripts/components/Board.js
  public/javascripts/components/Card.js
  public/javascripts/components/Column.js
Labels: bug, enhancement, feature, frontend

#150 [#148] bug(menuBtn) - 오타 수정
  public/javascripts/components/Header.js
Labels: bug, feature

#154 [#153] bug(serverTime) - 서버기준 시간 변경
  src/controller.js
Labels: backend, bug

#152 [#151] bug( activityTableUserName) - username 오류 문제 해결
  public/javascripts/components/LoginForm.js
Labels: backend, bug

#155 Feature/143 card edit auth
  public/javascripts/components/Card.js
  public/javascripts/components/Column.js
  public/javascripts/components/Header.js
  src/controller.js
Labels: enhancement, feature, frontend
